"""
Tabela de apoio: cidade-sede de seção eleitoral no exterior (como aparece no TSE) -> país (ISO3).
O TSE informa só a cidade; o país e o continente foram atribuídos manualmente.
"""

# ISO3 -> (nome do país em português, continente/região)
PAISES = {
    "AGO": ("Angola", "África"), "ALB": ("Albânia", "Europa"), "ARE": ("Emirados Árabes Unidos", "Oriente Médio"),
    "ARG": ("Argentina", "América do Sul"), "ARM": ("Armênia", "Ásia"), "ATG": ("Antígua e Barbuda", "América Central e Caribe"),
    "AUS": ("Austrália", "Oceania"), "AUT": ("Áustria", "Europa"), "AZE": ("Azerbaijão", "Ásia"),
    "BEL": ("Bélgica", "Europa"), "BEN": ("Benin", "África"), "BFA": ("Burkina Faso", "África"),
    "BGD": ("Bangladesh", "Ásia"), "BGR": ("Bulgária", "Europa"), "BHR": ("Bahrein", "Oriente Médio"),
    "BHS": ("Bahamas", "América Central e Caribe"), "BIH": ("Bósnia e Herzegovina", "Europa"), "BLZ": ("Belize", "América Central e Caribe"),
    "BOL": ("Bolívia", "América do Sul"), "BRB": ("Barbados", "América Central e Caribe"), "BWA": ("Botsuana", "África"),
    "CAN": ("Canadá", "América do Norte"), "CHE": ("Suíça", "Europa"), "CHL": ("Chile", "América do Sul"),
    "CHN": ("China", "Ásia"), "CIV": ("Costa do Marfim", "África"), "CMR": ("Camarões", "África"),
    "COD": ("Rep. Dem. do Congo", "África"), "COG": ("Congo", "África"), "COL": ("Colômbia", "América do Sul"),
    "CPV": ("Cabo Verde", "África"), "CRI": ("Costa Rica", "América Central e Caribe"), "CUB": ("Cuba", "América Central e Caribe"),
    "CYP": ("Chipre", "Europa"), "CZE": ("Tchéquia", "Europa"), "DEU": ("Alemanha", "Europa"),
    "DNK": ("Dinamarca", "Europa"), "DOM": ("República Dominicana", "América Central e Caribe"), "DZA": ("Argélia", "África"),
    "ECU": ("Equador", "América do Sul"), "EGY": ("Egito", "África"), "ESP": ("Espanha", "Europa"),
    "EST": ("Estônia", "Europa"), "ETH": ("Etiópia", "África"), "FIN": ("Finlândia", "Europa"),
    "FRA": ("França", "Europa"), "GAB": ("Gabão", "África"), "GBR": ("Reino Unido", "Europa"),
    "GEO": ("Geórgia", "Ásia"), "GHA": ("Gana", "África"), "GIN": ("Guiné", "África"),
    "GNB": ("Guiné-Bissau", "África"), "GNQ": ("Guiné Equatorial", "África"), "GRC": ("Grécia", "Europa"),
    "GTM": ("Guatemala", "América Central e Caribe"), "GUF": ("Guiana Francesa (França)", "América do Sul"),
    "GUY": ("Guiana", "América do Sul"), "HND": ("Honduras", "América Central e Caribe"), "HRV": ("Croácia", "Europa"),
    "HTI": ("Haiti", "América Central e Caribe"), "HUN": ("Hungria", "Europa"), "IDN": ("Indonésia", "Ásia"),
    "IND": ("Índia", "Ásia"), "IRL": ("Irlanda", "Europa"), "IRN": ("Irã", "Oriente Médio"),
    "IRQ": ("Iraque", "Oriente Médio"), "ISR": ("Israel", "Oriente Médio"), "ITA": ("Itália", "Europa"),
    "JAM": ("Jamaica", "América Central e Caribe"), "JOR": ("Jordânia", "Oriente Médio"), "JPN": ("Japão", "Ásia"),
    "KAZ": ("Cazaquistão", "Ásia"), "KEN": ("Quênia", "África"), "KOR": ("Coreia do Sul", "Ásia"),
    "KWT": ("Kuwait", "Oriente Médio"), "LBN": ("Líbano", "Oriente Médio"), "LBY": ("Líbia", "África"),
    "LCA": ("Santa Lúcia", "América Central e Caribe"), "LKA": ("Sri Lanka", "Ásia"), "MAR": ("Marrocos", "África"),
    "MEX": ("México", "América do Norte"), "MLI": ("Mali", "África"), "MMR": ("Mianmar", "Ásia"),
    "MOZ": ("Moçambique", "África"), "MWI": ("Malawi", "África"), "MYS": ("Malásia", "Ásia"),
    "NAM": ("Namíbia", "África"), "NGA": ("Nigéria", "África"), "NIC": ("Nicarágua", "América Central e Caribe"),
    "NLD": ("Países Baixos", "Europa"), "NOR": ("Noruega", "Europa"), "NPL": ("Nepal", "Ásia"),
    "NZL": ("Nova Zelândia", "Oceania"), "OMN": ("Omã", "Oriente Médio"), "PAK": ("Paquistão", "Ásia"),
    "PAN": ("Panamá", "América Central e Caribe"), "PER": ("Peru", "América do Sul"), "PHL": ("Filipinas", "Ásia"),
    "POL": ("Polônia", "Europa"), "PRK": ("Coreia do Norte", "Ásia"), "PRT": ("Portugal", "Europa"),
    "PRY": ("Paraguai", "América do Sul"), "PSE": ("Palestina", "Oriente Médio"), "QAT": ("Catar", "Oriente Médio"),
    "ROU": ("Romênia", "Europa"), "RUS": ("Rússia", "Europa"), "SAU": ("Arábia Saudita", "Oriente Médio"),
    "SEN": ("Senegal", "África"), "SGP": ("Singapura", "Ásia"), "SLV": ("El Salvador", "América Central e Caribe"),
    "SRB": ("Sérvia", "Europa"), "STP": ("São Tomé e Príncipe", "África"), "SUR": ("Suriname", "América do Sul"),
    "SVK": ("Eslováquia", "Europa"), "SVN": ("Eslovênia", "Europa"), "SWE": ("Suécia", "Europa"),
    "SYR": ("Síria", "Oriente Médio"), "TGO": ("Togo", "África"), "THA": ("Tailândia", "Ásia"),
    "TLS": ("Timor-Leste", "Ásia"), "TTO": ("Trinidad e Tobago", "América Central e Caribe"), "TUN": ("Tunísia", "África"),
    "TUR": ("Turquia", "Europa"), "TWN": ("Taiwan", "Ásia"), "TZA": ("Tanzânia", "África"),
    "UKR": ("Ucrânia", "Europa"), "URY": ("Uruguai", "América do Sul"), "USA": ("Estados Unidos", "América do Norte"),
    "VEN": ("Venezuela", "América do Sul"), "VNM": ("Vietnã", "Ásia"), "ZAF": ("África do Sul", "África"),
    "ZMB": ("Zâmbia", "África"), "ZWE": ("Zimbábue", "África"),
}

CIDADES = {
    "ABIDJÃ": "CIV", "ABU DHABI": "ARE", "ABUJA": "NGA", "ACCRA": "GHA", "ADIS ABEBA": "ETH", "AMSTERDÃ": "NLD",
    "AMÃ": "JOR", "ANCARA": "TUR", "ARGEL": "DZA", "ARTIGAS": "URY", "ASSUNÇÃO": "PRY", "ASTANA": "KAZ",
    "ATENAS": "GRC", "ATLANTA": "USA", "BAGDÁ": "IRQ", "BAKU": "AZE", "BAMAKO": "MLI", "BANGKOK": "THA",
    "BARCELONA": "ESP", "BAREIN": "BHR", "BEIRUTE": "LBN", "BELGRADO": "SRB", "BELMOPAN": "BLZ", "BERLIM": "DEU",
    "BISSAU": "GNB", "BOGOTÁ": "COL", "BOSTON": "USA", "BRATISLAVA": "SVK", "BRAZZAVILLE": "COG", "BRIDGETOWN": "BRB",
    "BRUXELAS": "BEL", "BUCARESTE": "ROU", "BUDAPESTE": "HUN", "BUENOS AIRES": "ARG", "CAIENA": "GUF", "CAIRO": "EGY",
    "CAMBERRA": "AUS", "CANTÃO": "CHN", "CARACAS": "VEN", "CASTRIES": "LCA", "CHICAGO": "USA", "CHUY": "URY",
    "CIDADE DO CABO": "ZAF", "CIUDAD DEL ESTE": "PRY", "CIUDAD GUAYANA": "VEN", "COBIJA": "BOL", "COCHABAMBA": "BOL",
    "COLOMBO": "LKA", "CONACRI": "GIN", "CONCEPCIÓN": "PRY", "COPENHAGUE": "DNK", "COTONOU": "BEN", "CÓRDOBA": "ARG",
    "DACAR": "SEN", "DACCA": "BGD", "DAMASCO": "SYR", "DAR ES SALAAM": "TZA", "DOHA": "QAT", "DUBLIN": "IRL",
    "DÍLI": "TLS", "EDIMBURGO": "GBR", "ENCARNACIÓN": "PRY", "ESTOCOLMO": "SWE", "FARO": "PRT", "FRANKFURT": "DEU",
    "GABORONE": "BWA", "GENEBRA": "CHE", "GEORGETOWN": "GUY", "GUATEMALA": "GTM", "HAMAMATSU": "JPN", "HANÓI": "VNM",
    "HARARE": "ZWE", "HARTFORD": "USA", "HAVANA": "CUB", "HELSINQUE": "FIN", "HONG KONG": "CHN", "HOUSTON": "USA",
    "IAUNDÊ": "CMR", "IEREVAN": "ARM", "IQUITOS": "PER", "ISLAMABADE": "PAK", "ISTAMBUL": "TUR", "JACARTA": "IDN",
    "KATMANDU": "NPL", "KIEV": "UKR", "KINGSTON-JAMAICA": "JAM", "KINSHASA": "COD", "KUAITE": "KWT",
    "KUALA LUMPUR": "MYS", "LA PAZ": "BOL", "LAGOS": "NGA", "LIBREVILLE": "GAB", "LILONGUE": "MWI", "LIMA": "PER",
    "LISBOA": "PRT", "LIUBLIANA": "SVN", "LOMÉ": "TGO", "LONDRES": "GBR", "LOS ANGELES": "USA", "LUANDA": "AGO",
    "LUSACA": "ZMB", "MADRI": "ESP", "MALABO": "GNQ", "MANILA": "PHL", "MANÁGUA": "NIC", "MAPUTO": "MOZ",
    "MARSELHA": "FRA", "MASCATE": "OMN", "MENDOZA": "ARG", "MEXICO": "MEX", "MIAMI": "USA", "MILÃO": "ITA",
    "MONTEVIDÉU": "URY", "MONTREAL": "CAN", "MOSCOU": "RUS", "MUMBAI": "IND", "MUNIQUE": "DEU", "NAGÓIA": "JPN",
    "NAIRÓBI": "KEN", "NASSAU": "BHS", "NICOSIA": "CYP", "NOVA DELHI": "IND", "NOVA YORK": "USA", "ORLANDO": "USA",
    "OSLO": "NOR", "OTTAWA": "CAN", "PANAMA": "PAN", "PARAMARIBO": "SUR", "PARIS": "FRA", "PASO LOS LIBRES": "ARG",
    "PEDRO JUAN CABALLERO": "PRY", "PEQUIM": "CHN", "PORT OF SPAIN": "TTO", "PORTO": "PRT", "PORTO PRÍNCIPE": "HTI",
    "PRAGA": "CZE", "PRAIA": "CPV", "PRETÓRIA": "ZAF", "PUERTO IGUAZÚ": "ARG", "PUERTO QUIJARRO": "BOL",
    "PYONGYANG": "PRK", "QUITO": "ECU", "RABAT": "MAR", "RAMALLAH": "PSE", "RIADE": "SAU", "RIO BRANCO": "URY",
    "RIVERA": "URY", "ROMA": "ITA", "SAINT JOHNS": "ATG", "SALTO DEL GUAIRÁ": "PRY", "SANTA CRUZ DE LA SIERRA": "BOL",
    "SANTA ELENA DE UAIRÉN": "VEN", "SANTIAGO": "CHL", "SARAJEVO": "BIH", "SEUL": "KOR", "SINGAPURA": "SGP",
    "ST GEORGES DE LOYAPOCK": "GUF", "SYDNEY": "AUS", "SÃO DOMINGOS": "DOM", "SÃO FRANCISCO": "USA",
    "SÃO JOSÉ": "CRI", "SÃO SALVADOR": "SLV", "SÃO TOMÉ": "STP", "SÓFIA": "BGR", "TAIPÉ": "TWN", "TALIN": "EST",
    "TBILISI": "GEO", "TEERÃ": "IRN", "TEGUCIGALPA": "HND", "TEL AVIV": "ISR", "TIRANA": "ALB", "TORONTO": "CAN",
    "TRÍPOLI": "LBY", "TUNIS": "TUN", "TÓQUIO": "JPN", "UAGADUGU": "BFA", "VANCOUVER": "CAN", "VARSÓVIA": "POL",
    "VIENA": "AUT", "WASHINGTON": "USA", "WELLINGTON": "NZL", "WINDHOEK": "NAM", "XANGAI": "CHN", "YANGON": "MMR",
    "ZAGREB": "HRV", "ZURIQUE": "CHE",
}
